### ISSUE TITLE
Cactus and sugarcane

### ISSUE THREAD

**Issue by ArturilloD** [gigaherz/ConfigurableReeds#8]
When this mod is added to Minecraft it makes cactus farms useless, the cacti do not break when they grow and also the cacti and sugar cane are no longer compostable.

As a request I would like to know if you plan to add compatibility with other mods such as extra reeds or similar.

**Comment by gigaherz** [comment]
Hmm... Thanks for the report, I'll look into that. there must be some explicit references to the vanilla blocks I'm not properly reassigning.
As for modded blocks, no I don't really have any plans for it, this was just a small utility mod I made by request, and I just maintain because I don't like to abandon mods, and it's easy to maintain.

**Comment by ArturilloD** [comment]
I understand, thank you. I would love to know how to program this, although
I don't really know where to start.
